# Workflow name
name: create-cloudformation-stack

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
jobs: # Jobs defined in the workflow
  create-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create CloudFormation Stack
      id: create_stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: udatest
        template: udatest.yml
    
    - name: Delete CloudFormation Stack on Create Failure
      if: steps.create_stack.outcome == 'failure'
      run: |
        echo "Stack creation failed. Cleaning up..."
        aws cloudformation delete-stack --stack-name udatest
        aws cloudformation wait stack-delete-complete --stack-name udatest
        